//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicament
    {
        public int Id { get; set; }
        public string MedicamentName { get; set; }
        public string Cost { get; set; }
        public string Count { get; set; }
        public string Price { get; set; }
        public string Date { get; set; }
        public string CategoryName { get; set; }
    }
}
